services:
  auth:
    container_name: auth
    build:
      dockerfile: ./app/Dockerfile
    networks:
      - gateway
      - internal

  dummy:
    container_name: dummy
    build: 
      dockerfile: ./dummyServer/Dockerfile
    ports:
    - 9703:9703
    networks:
      - internal


networks:
  gateway:
    external: true
    name: auth
  
  internal:
    external: false
      